### ISSUE TITLE
Use upstream debian package

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/monitorix_ynh#10]
monitorix has been (recently) package upstream into debian. It would be nice to install from the debian package instead of from source. 

Will try to build a stretch-backport.

**Comment by Josue-T** [comment]
Yes and no.

Monitorix still easy to install from the upstream. The advantage is to be able to have a more up to date package with the last monitorix version.

**Comment by anubister** [comment]
This is a general question for most of the Yunohost apps : 
get more up to date version vs get benefit of the Quality Assurance of Debian (rebuildability check, patchs, privacy...)
IMO for this specific app, according to the changelog, I would not expect fast evolution :-)
