### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/monitorix_ynh#11]
Your app is currently failing all tests on our CI.
https://ci-apps.yunohost.org/ci/job/2357

Unless the app is fixed before next Saturday, 13th, this app will be set at notworking.

**Comment by Josue-T** [comment]
Thanks for the information.

Should be fixed now

**Comment by anubister** [comment]
it seems this bug could be closed : https://ci-apps.yunohost.org/ci/apps/monitorix/
