### ISSUE TITLE
Install fails on a 'grep" loop

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/monitorix_ynh#12]
On update, the script is stuck waiting for a message from a `grep` command, in a `for` loop.
See log https://paste.yunohost.org/raw/qefaquhama

I run last ynh stable, on a x86 VPS. Good luck for the fix !

**Comment by Josue-T** [comment]
Hello,

Well, this loop is "normal", it's just waiting untils the serice is correctly started. Did the upgrade fail ?

**Comment by Jaxom99** [comment]
OK yeah, it was just taking (wayyy) longer than I thought it would :S 
Sorry for opening this one, at least I learned something !
