### ISSUE TITLE
Update failed : restore sends 404 

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/monitorix_ynh#14]
The upgrade failed (nginx reload sent an error because an onld domain was badly removed), and failed to restore backup. In the restore logs, I see a "404 error", and it turns out the .deb used for restoration is not found : https://www.monitorix.org/monitorix_3.11.0-izzy1_all.deb

The correct URL is now : https://www.monitorix.org/monitorix_3.12.0-izzy1_all.deb . How can we fix this ?

**Comment by Jaxom99** [comment]
So I followed this path :

- find the old deb 3.11 URL, hopefully listed in https://apt.izzysoft.de/ubuntu/dists/generic/
- untar the monitorix-pre-upgrade file present in /home/yunohost.backup/archives
- change the file `apps/monitorix/settings/conf/app.src` to the new URL of the old 3.11 deb
- re-tar **all the files** (apps/ directory PLUS backup.csv and info.json) into a monitorix-pre-upgrade.tar.json
- call the `yunohost backup restore` command.

And as I fixed my nginx trouble in between, the upgrade went well also.

**Comment by Josue-T** [comment]
Normally on the master  branch you should find the last version 3.12 available on the repository.

**Comment by Jaxom99** [comment]
yep, the upgrade was proposed by ynh, and then I encountered a bug (in ynh core, not your package). I'm running 3.12 now, all is good :)

**Comment by Jaxom99** [comment]
Different error, same failed upgrade then restore on another machine (RPi). Log parts that could be of help :
```
2020-03-19 15:04:20,280: WARNING - dpkg: dependency problems prevent configuration of monitorix:
2020-03-19 15:04:20,282: WARNING -  monitorix depends on libxml-libxml-perl; however:
2020-03-19 15:04:20,283: WARNING -   Package libxml-libxml-perl is not installed.
2020-03-19 15:04:20,285: WARNING - 
2020-03-19 15:04:20,286: WARNING - dpkg: error processing package monitorix (--install):
2020-03-19 15:04:20,287: WARNING -  dependency problems - leaving unconfigured
```

**Comment by Josue-T** [comment]
Hello, Can you try from the testing branch here : https://github.com/YunoHost-Apps/monitorix_ynh/tree/testing

With this command : `yunohost app upgrade monitorix -u https://github.com/YunoHost-Apps/monitorix_ynh/tree/testing`

**Comment by Jaxom99** [comment]
So, I restored 3.11 using my previous fix, and upgraded with the testing branch : it works 😄  Do you want the log though ?

**Comment by Josue-T** [comment]
> So, I restored 3.11 using my previous fix, and upgraded with the testing branch : it works smile Do you want the log though ?

No thank. Thanks for you feedback.

**Comment by Jaxom99** [comment]
❤️ 👍
