### ISSUE TITLE
Monitorix, plusieurs instances en même temps, un bug ?

### ISSUE THREAD

**Issue by Flashpok** [YunoHost-Apps/monitorix_ynh#30]
### Describe the bug

Après l'installation de Monitorix via Yunohost, le package apparaît à plusieurs reprises dans l'Activity Monitor, et il envoie deux notifications par email quotidiennes. J'ai donc l'impression qu'il y a un souci.

Par exemple, si je check le statut du service monitorix via le shell, j'ai ceci :+1: 

```
   CGroup: /system.slice/monitorix.service
           ├─2277 /usr/bin/monitorix -c /etc/monitorix/monitorix.conf -p /var/run/monitorix.pid
           ├─2723 /usr/bin/monitorix -c /etc/monitorix/monitorix.conf -p /var/run/monitorix.pid
```

un autre indice : Si je désactive le service via le tableau des Services (interface d'administration), je vois qu'il y a néanmoins encore de l'activité dans HTOP.

Je ne sais pas si c'est un bug ?
Merci de votre lecture.

**Comment by Josue-T** [comment]
Hello,

Sometime I detected the same issue. I don't really know what is happening internally on the process. It's mainly an upstream issue as Yunohost just use the debian package from upstream. You can create an issue about this here: https://github.com/mikaku/Monitorix/issues

**Comment by Josue-T** [comment]
Should be fixed by #47
