### ISSUE TITLE
Error during upgrade: "Unknown database 'monitorix'" when selecting the database

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/monitorix_ynh#40]
Monitorix works, I can see data spanning more than one year.

![image](https://user-images.githubusercontent.com/3952726/202189012-83b67c57-82d5-4b9b-ad9d-de9377ad5917.png)

The upgrade script fails to perform a backup, therefore not upgrading monitorix from `3.12.0~ynh2` to `3.14.0~ynh2`.

Ynh 11 bare metal (x86_64). I have full access to the system.

Logs: https://paste.yunohost.org/raw/igagilekir

**Comment by Josue-T** [comment]
I think it's linked to #32 and #34. Monitorix never needed a database. The easiest way it maybe to remove the line which backup the db into the backup script.

**Comment by MayeulC** [comment]
I commented `ynh_mysql_dump_db --database="$db_name" > db.sql` in `/etc/yunohost/apps/monitorix/scripts/backup`, and it went further, but I forgot to comment it out in the restore script, and the upgrade failed again:

```
2022-11-17 10:54:14,716: DEBUG - nov. 17 10:54:14 nginx[1553622]: nginx: [emerg] invalid port in upstream "127.0.0.1:/monitorix" in /etc/nginx/conf.d/maindomain.tld.d/monitorix.conf:2
```

https://paste.yunohost.org/raw/erulayaxec

I'll edit the backup to remove that line for the restore script as well.
