### ISSUE TITLE
Upgrade fails when reloading nginx with "invalid port in upstream"

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/monitorix_ynh#41]
```
2022-11-17 10:54:14,716: DEBUG - nov. 17 10:54:14 nginx[1553622]: nginx: [emerg] invalid port in upstream "127.0.0.1:/monitorix" in /etc/nginx/conf.d/maindomain.tld.d/monitorix.conf:2
```

https://paste.yunohost.org/raw/erulayaxec

More recent attempt:
https://paste.yunohost.org/raw/ufahozocuk

_Originally posted by @MayeulC in https://github.com/YunoHost-Apps/monitorix_ynh/issues/40#issuecomment-1318383205_

**Comment by MayeulC** [comment]
Still an issue: https://paste.yunohost.org/raw/hahofuxima

**Comment by MayeulC** [comment]
It failed restoring too: https://paste.yunohost.org/raw/piyupoqule

Looking at the log, `//tmp/tmp.0CDrYHYynC/app.deb` is obviously invalid, and only `/tmp/tmp.0CDrYHYynC/app` exists.

**Comment by MayeulC** [comment]
SOLVED!

I only had the `port: 8081` yunohost setting; the `http_port` setting was not set.

I suggest:
* setting `set -u` to disallow empty variables in bash. This may have side effects in the scripts, luckily the CI should catch these, and it should be easy to check. Maybe even [`set -euox pipefail`](https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425)
* in the upgrade script, migrate from the old "port" to the new "http_port" yunohost setting variable

**Comment by Josue-T** [comment]
Closing as theses settings was mainly reworked with packaging v2 and #55
